kind: Service
apiVersion: v1
metadata:
  name: alertmanager-zabbix-webhook
  namespace: monitoring
spec:
  selector:
    app: alertmanager-zabbix-webhook
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager-zabbix-webhook
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alertmanager-zabbix-webhook
    spec:
      restartPolicy: Always
      containers:
      - name: webhook
        image: gmauleon/alertmanager-zabbix-webhook:0.2.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 10Mi
            cpu: 0.1
          limits:
            memory: 10Mi
            cpu: 0.1
        volumeMounts:
        - mountPath: /etc/webhook/config.yaml
          name: alertmanager-zabbix-webhook-config
          subPath: config-webhook.yaml
          #      imagePullSecrets:
          #        - name: myprivatereposecret
      volumes:
      - name: alertmanager-zabbix-webhook-config
        configMap:
          name: alertmanager-zabbix-webhook-config
