apiVersion: v1
kind: Pod
metadata:
  name: alertmanager-zabbix
spec:
  restartPolicy: Always
  containers:
  - name: provisioner
    image: gmauleon/alertmanager-zabbix-provisioner
    imagePullPolicy: Always
    env:
    - name: ZABBIX_API_USER
      valueFrom:
        secretKeyRef:
          name: alertmanager-zabbix-secret
          key: zabbixApiUser
    - name: ZABBIX_API_PASSWORD
      valueFrom:
        secretKeyRef:
          name: alertmanager-zabbix-secret
          key: zabbixApiPassword
    resources:
      requests:
        memory: 10Mi
        cpu: 0.1
      limits:
        memory: 10Mi
        cpu: 0.1
    volumeMounts:
    - mountPath: /etc/provisioner/config.yaml
      name: alertmanager-zabbix-config
      subPath: config-provisioner.yaml
    - mountPath: /etc/provisioner/ca.pem
      name: alertmanager-zabbix-config
      subPath: ca.pem
  - name: webhook
    image: gmauleon/alertmanager-zabbix-webhook
    imagePullPolicy: Always
    #imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 10Mi
        cpu: 0.1
      limits:
        memory: 10Mi
        cpu: 0.1
    volumeMounts:
    - mountPath: /etc/webhook/config.yaml
      name: alertmanager-zabbix-config
      subPath: config-webhook.yaml
  volumes:
  - name: alertmanager-zabbix-config
    configMap:
      name: alertmanager-zabbix-config
