apiVersion: v1
kind: Pod
metadata:
  name: alertmanager-zabbix
spec:
  containers:
  - name: provisioner
    image: gmauleon/alertmanager-zabbix-provisioner
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 10Mi
        cpu: 0.1
      limits:
        memory: 10Mi
        cpu: 0.1
  restartPolicy: Always
  - name: webhook
    image: gmauleon/alertmanager-zabbix-webhook
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 10Mi
        cpu: 0.1
      limits:
        memory: 10Mi
        cpu: 0.1
  restartPolicy: Always
