global:
  resolve_timeout: 1m
route:
  receiver: 'zabbix'
  group_by:
    - 'job'
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 30s
receivers:
- name: 'zabbix'
  webhook_configs:
    - url: http://127.0.0.1:8080/alerts
      send_resolved: true
